### ISSUE TITLE
[unixdump]AttributeError: module 'fcntl' has no attribute 'F_SETPIPE_SZ'

### ISSUE THREAD

**Issue by salmon5** [nccgroup/ebpf#4]
Hi,unixdump not work on Almalinux8.6/Almalinux9.0
Version:1.2.0
Install method:pip3 install unixdump
Error info:
[root@k8s-node4 ~]# unixdump
Traceback (most recent call last):
  File "/usr/local/bin/unixdump", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/unixdump/__init__.py", line 1793, in main
    fcntl.fcntl(pipe_in[1], fcntl.F_SETPIPE_SZ, log_buf_size*2)
AttributeError: module 'fcntl' has no attribute 'F_SETPIPE_SZ'

Version 1.1.1 works well.

Thanks.
